### ISSUE TITLE
Enable self contained build - provision SBT

### ISSUE THREAD

**Issue by mockitoguy** [linkedin/play-parseq#11]
In order to cleanly integrate with CI can we get SBT automatically provisioned in a similar fashion as Gradle wrapper works? Does SBT has a concept of wrapper (or 'sbtw')?

@FranklinYinanDing, can you take a look at this a send a PR?

**Comment by FranklinYinanDing** [comment]
Found some documentation about this. https://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html

Working on it.

**Comment by mockitoguy** [comment]
Great! Thank you!

Let's aim for a solution that is decoupled from the CI system. Check out this SO question: https://stackoverflow.com/questions/37295128/run-sbt-without-installing-it-first Apparently, there is a way to create completely self-contained build environment with SBT, just like we have with Gradle wrapper.

If we decouple from Travis CI, we can easily swap the CI if needed. Plus, wrapper-like SBT execution will be helpful for developers, too.

**Comment by FranklinYinanDing** [comment]
I see. For sbt, the simplest way is to include sbt-launcher.jar, which is the core of `sbt`, then call `java <opts> -jar sbt-launcher.jar` to get into the sbt.

Any general wrappers would need to download a specific version of sbt-launcher, while they do provide more friendly script.

I am somewhat not a fan of re-downloading sbt-launcher.jar (> 1MB) every time. I can create a PR to attach the sbt-launcher.jar, and we can also use that jar in Travis CI.

What do you think?

**Comment by mockitoguy** [comment]
Thank you for looking into it!

Ideally, we have one command to run the build and we used that command on CI. In my PR, I created in a "build.sh" file, do you want to make this change into this file and commit/push to my PR?

**Comment by FranklinYinanDing** [comment]
Updated. See the last commit of #10

**Comment by FranklinYinanDing** [comment]
Merged in #10
