### ISSUE TITLE
Travis CI timeout when publishing

### ISSUE THREAD

**Issue by mockitoguy** [linkedin/play-parseq#16]
Travis CI timed out when publishing.

@FranklinYinanDing, can you make following local test on clean checkout of play-parseq?

```
export BINTRAY_API_KEY=your-secret
./gradlew bintrayUpload -PdryRun
./gradlew bintrayUpload
```

Above should work and should publish to LinkedIn Bintray test repo (https://bintray.com/linkedin/test-repo/play-parseq).

Once we get Bintray publications working we can:
 - delete v.0.8.1 tag & push
 - revert v.0.8.1 code push performed by Shipkit & push
 - trigger Travis to build new version

Once we get Travis to automatically publish without problems we can:
 - clean up the repo again (remove tag and automated commit)
 - change the 'test-repo' to 'maven' in shipkit.gradle & push
 - observe how Travis builds new version and ships to JCenter :D

Then, let's work on Maven Central releases.

**Comment by FranklinYinanDing** [comment]
@mockitoguy I tested successfully and cleaned up. We can start moving to maven. 💯

**Comment by mockitoguy** [comment]
It must have been some flakiness, let's move one.
