### ISSUE TITLE
Create 'com.linkedin.play-parseq' project in Maven Central

### ISSUE THREAD

**Issue by mockitoguy** [linkedin/play-parseq#18]
To start publishing to Maven Central we need to follow the official guide:

http://central.sonatype.org/pages/ossrh-guide.html

@FranklinYinanDing, it's best if you or one of the team members do it. This way you'll learn the process and can manage/maintain it long term. I can help. The link above should get you a good start. Once you created project for Maven Central, you can generate key+password and we will use to configure Shipkit to automatically publish to Maven Central.

**Comment by FranklinYinanDing** [comment]
It is ready. https://issues.sonatype.org/browse/OSSRH-38862
