### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by FranklinYinanDing** [linkedin/play-parseq#20]
Now we've successfully published to Bintray. We need to include the project with JCenter then sync with Maven Central.

**Comment by FranklinYinanDing** [comment]
@mockitoguy I have sent the request to be included in JCenter from Bintray package management page. Is there anything should be done other than waiting?

**Comment by FranklinYinanDing** [comment]
The request for JCenter is approved.

**Comment by mockitoguy** [comment]
Great! Once play-parseq is included in JCenter, we're half way to Maven Central.

Once your Maven Central JIRA ticket is approved, you can release to Maven Central from Bintray UI, user your Nexus OSS id / password.

**Comment by FranklinYinanDing** [comment]
Both are done. Please see PR #21
