### ISSUE TITLE
Not sync with Maven Central

### ISSUE THREAD

**Issue by FranklinYinanDing** [linkedin/play-parseq#24]
The artifacts are not showing in Maven Central. Contacted with Sonatype, they are not seeing traces on oss.sonatype.org. See [here](https://issues.sonatype.org/browse/OSSRH-38862?focusedCommentId=475999&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-475999).

**Comment by FranklinYinanDing** [comment]
@mockitoguy Do you happen to know what's wrong? Is shipkit not doing the job right?

**Comment by mockitoguy** [comment]
@FranklinYinanDing, I believe we have fixed it by now, right?
